<a href="https://colab.research.google.com/github/bucks-hub/pytorch/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A torch.Tesnor is a multim-dimensional matrix containing elements of single datatype.

default datatype is **float32**



*   Tensrs are more suitable for deep learning than numpy arrays.













In [4]:
import torch
import numpy as np

In [2]:
list = [[1,2,3,4], [5,6,7,8]]
list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
arry = np.random.rand(5,5)
print(arry)
arry.dtype

[[0.86763235 0.85066394 0.37566367 0.94788767 0.13778174]
 [0.47172015 0.81182807 0.26756026 0.66822331 0.93881069]
 [0.77846298 0.09437478 0.29992178 0.48712126 0.37872536]
 [0.85829342 0.45836968 0.01684327 0.88639414 0.86802771]
 [0.51328046 0.64270258 0.95221625 0.98847749 0.64591472]]


dtype('float64')

In [13]:
tens2d = torch.randn(5,6)
print(tens2d)
print(tens2d.dtype)

tensor([[-0.1487, -0.5146, -0.4514, -0.9999, -0.2390,  0.3954],
        [ 0.5128,  0.3092, -0.7064, -0.5680, -0.1412, -0.2022],
        [ 1.7901,  0.8986, -0.6384, -1.0832,  0.1590,  1.8452],
        [-0.4484, -0.2569, -0.1788, -1.2701, -0.1766, -1.0482],
        [-0.0630, -0.4317, -1.0182,  0.1746,  1.8557,  1.7691]])
torch.float32


In [14]:
tens3d = torch.randn(3,7,8)
print(tens3d)

tensor([[[ 0.9544, -1.3801,  0.1705, -0.1603,  0.4655, -1.3136, -0.2520,
          -0.1594],
         [-0.3042,  0.2798, -1.6220,  0.5198,  1.3341, -1.4302,  0.3890,
          -0.8381],
         [ 1.1292,  1.9709, -1.7017,  0.1083,  1.9057, -0.5557, -0.4516,
           0.9399],
         [-0.0592, -0.1325, -0.4074, -0.0684,  1.0524, -0.3109,  1.0941,
          -0.7505],
         [ 0.6479,  0.4306, -0.0710, -0.9456, -1.0066,  0.8515, -1.0208,
          -0.2133],
         [ 0.9460, -0.1521,  0.0749,  2.2721,  0.4956, -0.5132, -1.3600,
          -0.6173],
         [ 0.4275,  1.3163,  0.3251,  1.1025, -0.1009,  0.1289,  2.3770,
           2.1353]],

        [[ 1.1936,  1.0977, -0.7911,  0.1893, -0.2184, -1.7526, -0.0054,
          -0.5799],
         [-1.4733,  0.8058, -0.4066, -1.4995, -1.0322,  0.7839, -0.1150,
          -0.1444],
         [ 0.0427, -0.0766,  0.6874, -0.2105,  0.6710, -0.0310,  0.1999,
          -0.0715],
         [-0.0099, -0.6189,  0.9046,  0.0062,  0.4903, -1.0106, -1.0

In [15]:
tens3d_1 = torch.zeros(3,7,8)
print(tens3d_1)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])
